version: 2

builds:
  -
    binary: watchducker
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
